package io.evotrace.server.ai;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.evotrace.server.change.ChangeEvent;
import io.evotrace.server.change.ChangeEventRepository;
import io.evotrace.server.change.ChangeFile;
import io.evotrace.server.change.ChangeFileRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import io.evotrace.server.ingestion.BlobStoreService;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;
import java.util.regex.Pattern;

/**
 * AI Code Review Engine — 深度审查 AI 生成的代码变更。
 *
 * 能力：
 * 1. 检测提交是否由 AI 生成（commit message 模式、author、co-author）
 * 2. 分析 diff 的业务逻辑变更
 * 3. 检测潜在 Bug / 安全漏洞 / 性能问题 / 代码风格
 * 4. 生成结构化审查报告（PASS / WARNING / FAIL）
 */
@Component
public class CodeReviewEngine {

    private static final Logger log = LoggerFactory.getLogger(CodeReviewEngine.class);
    private static final ObjectMapper mapper = new ObjectMapper();

    // AI 提交检测模式
    private static final Pattern AI_COMMIT_PATTERN = Pattern.compile(
            "(?i).*(Co-Authored-By|Co-authored-by).*(Claude|Copilot|Cursor|CodeBuddy|ChatGPT|GPT|Gemini|Codex|AI|agent).*"
    );
    private static final Pattern AI_MESSAGE_PATTERN = Pattern.compile(
            "(?i).*(generated by|written by|created by|auto.?generated|ai.?generated|claude|copilot|cursor|chatgpt|gpt-4|gemini).*"
    );
    private static final List<String> AI_AUTHOR_PATTERNS = List.of(
            "claude", "copilot", "cursor", "codebuddy", "chatgpt", "gemini", "noreply@anthropic",
            "noreply@github", "bot", "codex", "aide", "cody"
    );

    private final JdbcTemplate jdbc;
    private final ChangeEventRepository changeEventRepository;
    private final ChangeFileRepository changeFileRepository;
    private final ModelRouter modelRouter;
    private final PromptLoader promptLoader;
    private final BlobStoreService blobStore;

    @Value("${evotrace.code-review.max-diff-chars:12000}")
    private int maxDiffChars;

    public CodeReviewEngine(JdbcTemplate jdbc, ChangeEventRepository changeEventRepository,
                            ChangeFileRepository changeFileRepository,
                            ModelRouter modelRouter, PromptLoader promptLoader,
                            BlobStoreService blobStore) {
        this.jdbc = jdbc;
        this.changeEventRepository = changeEventRepository;
        this.changeFileRepository = changeFileRepository;
        this.modelRouter = modelRouter;
        this.promptLoader = promptLoader;
        this.blobStore = blobStore;
    }

    /**
     * 检测提交是否由 AI 生成。
     */
    public AiDetectionResult detectAiGenerated(ChangeEvent event) {
        String message = event.getCommitMessage();
        String author = event.getAuthor();
        // Fallback for events persisted before commit_message was stored:
        // check the AI summary content (may mention AI authorship)
        if (message == null || message.isBlank()) {
            try {
                List<Map<String, Object>> rows = jdbc.queryForList(
                        "SELECT s.content FROM ai_semantic_unit s WHERE s.target_type='CHANGE_EVENT' AND s.target_id=? AND s.kind='SUMMARY'",
                        event.getEventId());
                if (!rows.isEmpty()) message = (String) rows.get(0).getOrDefault("content", "");
            } catch (Exception ignored) {}
        }

        String aiSource = null;
        boolean aiGenerated = false;

        // 1. Check Co-Authored-By
        if (AI_COMMIT_PATTERN.matcher(message).matches()) {
            aiGenerated = true;
            if (message.toLowerCase().contains("claude")) aiSource = "claude";
            else if (message.toLowerCase().contains("copilot")) aiSource = "copilot";
            else if (message.toLowerCase().contains("cursor")) aiSource = "cursor";
            else if (message.toLowerCase().contains("codebuddy")) aiSource = "codebuddy";
            else aiSource = "ai-unknown";
        }

        // 2. Check commit message pattern
        if (!aiGenerated && AI_MESSAGE_PATTERN.matcher(message).matches()) {
            aiGenerated = true;
            aiSource = detectSource(message);
        }

        // 3. Check author
        if (!aiGenerated && author != null) {
            String lowerAuthor = author.toLowerCase();
            for (String pattern : AI_AUTHOR_PATTERNS) {
                if (lowerAuthor.contains(pattern)) {
                    aiGenerated = true;
                    aiSource = pattern.equals("noreply@anthropic") ? "claude" : pattern;
                    break;
                }
            }
        }

        return new AiDetectionResult(aiGenerated, aiSource);
    }

    /**
     * Run a full code review on a change event (manual trigger).
     */
    public Map<String, Object> review(String eventId) {
        return review(eventId, "MANUAL");
    }

    /**
     * Run a full code review on a change event.
     *
     * @param reviewType trigger source: MANUAL / AUTO / PR
     */
    @Transactional
    public Map<String, Object> review(String eventId, String reviewType) {
        ChangeEvent event = changeEventRepository.findByEventId(eventId).orElse(null);
        if (event == null) return Map.of("error", "change event not found: " + eventId);

        // Check existing review
        Integer existing = jdbc.queryForObject(
                "SELECT count(*) FROM ai_code_review WHERE change_event_id = ?", Integer.class, eventId);
        if (existing != null && existing > 0) {
            return getReviewReport(eventId);
        }

        // Detect if AI-generated
        AiDetectionResult aiResult = detectAiGenerated(event);

        // Get changed files; include the real diff from blob storage when available
        List<ChangeFile> files = changeFileRepository.findByEventId(eventId);
        String diff = buildDiffContext(files);
        int totalLines = files.stream().mapToInt(f -> f.getAddLines() + f.getDelLines()).sum();

        // Build prompt for AI review
        String reviewPrompt = buildReviewPrompt(event, files, aiResult, diff);

        // Call AI for structured review (skip if no API key configured)
        CodeReviewResult result = null;
        String apiKey = System.getenv("AI_API_KEY");
        if (apiKey != null && !apiKey.isBlank() && !"sk-placeholder".equals(apiKey)) {
            try {
                ChatClient client = modelRouter.clientFor("CODE_REVIEW");
                result = client.prompt().user(reviewPrompt).call().entity(CodeReviewResult.class);
            } catch (Exception e) {
                log.warn("AI review call failed, using heuristic: {}", e.getMessage());
            }
        } else {
            log.info("No AI API key configured, using heuristic review for event {}", eventId);
        }

        if (result == null) {
            result = heuristicReview(event, files, aiResult);
        }

        // Persist review
        Long reviewId = persistReview(event, aiResult, result, reviewType);

        // Persist individual findings
        if (result.findings() != null) {
            for (var finding : result.findings()) {
                persistFinding(reviewId, finding);
            }
        }

        // Update stats
        updateStats(event.getProjectId(), aiResult, totalLines, result.score(), result.verdict());

        log.info("code review complete: event={} type={} aiGenerated={} verdict={} score={} findings={}",
                eventId, reviewType, aiResult.aiGenerated(), result.verdict(), result.score(),
                result.findings() != null ? result.findings().size() : 0);

        return getReviewReport(eventId);
    }

    /**
     * Build the diff context for the AI prompt: real diff content from blob
     * storage when available, otherwise a per-file line-count summary.
     * Truncated to {@code evotrace.code-review.max-diff-chars} overall.
     */
    private String buildDiffContext(List<ChangeFile> files) {
        StringBuilder diffCtx = new StringBuilder();
        for (ChangeFile f : files) {
            if (diffCtx.length() >= maxDiffChars) {
                diffCtx.append("\n[diff truncated]\n");
                break;
            }
            String realDiff = f.getDiffBlobRef() != null ? blobStore.get(f.getDiffBlobRef()) : null;
            if (realDiff != null && !realDiff.isBlank()) {
                diffCtx.append(String.format("--- %s [%s] (+%d -%d)\n",
                        f.getFilePath(), f.getChangeKind(), f.getAddLines(), f.getDelLines()));
                int room = maxDiffChars - diffCtx.length();
                diffCtx.append(realDiff.length() <= room
                        ? realDiff : realDiff.substring(0, Math.max(0, room)) + "\n[diff truncated]\n");
            } else {
                // Blob unavailable (in-memory store lost on restart) — degrade to summary line
                diffCtx.append(String.format("  [%s] %s (+%d -%d)\n", f.getChangeKind(), f.getFilePath(),
                        f.getAddLines(), f.getDelLines()));
            }
        }
        return !diffCtx.isEmpty() ? diffCtx.toString() : "(empty diff)";
    }

    /**
     * Get an existing review report with all findings.
     */
    public Map<String, Object> getReviewReport(String eventId) {
        Map<String, Object> review = jdbc.queryForMap(
                "SELECT * FROM ai_code_review WHERE change_event_id = ?", eventId);
        List<Map<String, Object>> findings = jdbc.queryForList(
                "SELECT * FROM review_finding WHERE review_id = ? ORDER BY CASE severity " +
                "WHEN 'CRITICAL' THEN 0 WHEN 'WARNING' THEN 1 ELSE 2 END",
                review.get("id"));
        review.put("findings", findings);

        // Count by severity
        long critical = findings.stream().filter(f -> "CRITICAL".equals(f.get("severity"))).count();
        long warnings = findings.stream().filter(f -> "WARNING".equals(f.get("severity"))).count();
        long infos = findings.stream().filter(f -> "INFO".equals(f.get("severity"))).count();
        long suggestions = findings.stream().filter(f -> "SUGGESTION".equals(f.get("severity"))).count();
        review.put("criticalCount", critical);
        review.put("warningCount", warnings);
        review.put("infoCount", infos);
        review.put("suggestionCount", suggestions);

        return review;
    }

    /**
     * List review history for a project.
     */
    public List<Map<String, Object>> listReviews(Long projectId, int limit) {
        return jdbc.queryForList("""
                SELECT r.id, r.change_event_id AS "eventId", r.ai_generated AS "aiGenerated",
                       r.ai_source AS "aiSource", r.overall_score AS "score",
                       r.overall_verdict AS "verdict", r.diff_summary AS "summary",
                       (SELECT count(*) FROM review_finding WHERE review_id = r.id) AS "findingCount",
                       r.reviewed_at AS "reviewedAt"
                FROM ai_code_review r WHERE r.project_id = ?
                ORDER BY r.reviewed_at DESC LIMIT ?
                """, projectId, limit);
    }

    /**
     * Get AI commit statistics.
     */
    public List<Map<String, Object>> getStats(Long projectId, int days) {
        return jdbc.queryForList("""
                SELECT stat_date AS "date", ai_source AS "source", commit_count AS "commits",
                       total_lines AS "lines", review_pass_rate AS "passRate", avg_score AS "avgScore"
                FROM ai_commit_stats
                WHERE project_id = ? AND stat_date >= CURRENT_DATE - ?
                ORDER BY stat_date DESC, commit_count DESC
                """, projectId, days);
    }

    // ==================== Private helpers ====================

    private String buildReviewPrompt(ChangeEvent event, List<ChangeFile> files,
                                      AiDetectionResult aiResult, String diff) {
        return String.format("""
                You are a senior code reviewer. Analyze the following code diff and produce a structured review.

                Context:
                - Change type: %s
                - Author: %s
                - AI-generated: %s (%s)
                - Files changed: %d
                - Branch: %s

                Diff:
                %s

                Review carefully for:
                1. BUG: potential logic errors, null pointers, race conditions, incorrect error handling
                2. SECURITY: injection risks, missing auth, exposed secrets, unsafe deserialization
                3. PERFORMANCE: N+1 queries, memory leaks, unnecessary allocations, blocking I/O
                4. LOGIC: business rule violations, incorrect state transitions, edge cases
                5. STYLE: naming, structure, anti-patterns, missing tests
                6. DEPENDENCY: version conflicts, deprecated API usage, license issues

                Respond with JSON ONLY:
                {
                  "score": 0-100,
                  "verdict": "PASS"|"WARNING"|"FAIL",
                  "diffSummary": "one-sentence business logic summary",
                  "logicAnalysis": "what the change does and why",
                  "suggestion": "overall improvement suggestion or empty string",
                  "findings": [
                    {
                      "severity": "CRITICAL"|"WARNING"|"INFO"|"SUGGESTION",
                      "category": "BUG"|"SECURITY"|"PERFORMANCE"|"LOGIC"|"STYLE"|"DEPENDENCY",
                      "filePath": "...",
                      "lineRange": "L45-L52",
                      "title": "short title",
                      "description": "detailed explanation",
                      "codeSnippet": "the problematic code",
                      "suggestion": "how to fix",
                      "autoFixable": true|false
                    }
                  ]
                }
                """, event.getEventType(), event.getAuthor(), aiResult.aiGenerated(),
                aiResult.aiSource() != null ? aiResult.aiSource() : "N/A",
                files.size(), event.getBranch() != null ? event.getBranch() : "unknown", diff);
    }

    private CodeReviewResult heuristicReview(ChangeEvent event, List<ChangeFile> files,
                                              AiDetectionResult aiResult) {
        List<Finding> findings = new ArrayList<>();
        int score = 80;

        // Heuristic: large files → warning
        for (ChangeFile f : files) {
            if (f.getAddLines() + f.getDelLines() > 500) {
                findings.add(new Finding("WARNING", "STYLE", f.getFilePath(), null,
                        "文件变更量过大 (" + (f.getAddLines() + f.getDelLines()) + " 行)",
                        "大文件变更难以审查，建议拆分为多个小提交",
                        null, "拆分为多个逻辑独立的 commit", false));
                score -= 10;
            }
            if (f.getAddLines() > 0 && f.getDelLines() == 0 && f.getFilePath() != null
                    && f.getFilePath().endsWith(".java")) {
                // Check for missing tests
                String path = f.getFilePath();
                String testPath = path.replace("src/main/java", "src/test/java")
                        .replace(".java", "Test.java");
                boolean hasTest = files.stream().anyMatch(f2 ->
                        f2.getFilePath() != null && f2.getFilePath().contains("Test"));
                if (!hasTest && !path.contains("Test")) {
                    findings.add(new Finding("SUGGESTION", "STYLE", f.getFilePath(), null,
                            "新增代码缺少对应的单元测试",
                            "建议为新增逻辑编写单元测试，确保边界情况覆盖",
                            null, "添加单元测试覆盖新增逻辑", false));
                    score -= 5;
                }
            }
        }

        // Heuristic: config changes
        boolean hasConfigChange = files.stream().anyMatch(f ->
                f.getFilePath() != null && (f.getFilePath().endsWith(".yml") ||
                        f.getFilePath().endsWith(".yaml") || f.getFilePath().endsWith(".properties")));
        if (hasConfigChange) {
            findings.add(new Finding("INFO", "LOGIC", null, null,
                    "配置文件发生变更", "请确认配置项变更不包含敏感信息（密码/密钥/Token）",
                    null, "检查敏感值是否已脱敏", false));
        }

        // Heuristic: DDL changes
        boolean hasDdl = files.stream().anyMatch(f ->
                f.getFilePath() != null && f.getFilePath().endsWith(".sql"));
        if (hasDdl) {
            findings.add(new Finding("WARNING", "PERFORMANCE", null, null,
                    "数据库迁移脚本变更", "请确认 DDL 变更已添加合适的索引，并在非高峰期执行",
                    null, "评估 DDL 对生产环境的影响", false));
            score -= 10;
        }

        score = Math.max(0, Math.min(100, score));
        String verdict = score >= 70 ? "PASS" : score >= 50 ? "WARNING" : "FAIL";

        return new CodeReviewResult(score, verdict,
                "变更涉及 " + files.size() + " 个文件",
                "自动启发式审查（AI 模型未配置或调用失败），请人工复审",
                findings.isEmpty() ? "" : "建议人工复审以上发现项",
                findings);
    }

    private Long persistReview(ChangeEvent event, AiDetectionResult aiResult,
                               CodeReviewResult result, String reviewType) {
        jdbc.update("""
                INSERT INTO ai_code_review(project_id, change_event_id, review_type, ai_generated, ai_source,
                    diff_summary, logic_analysis, overall_score, overall_verdict, suggestion)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """, event.getProjectId(), event.getEventId(), reviewType, aiResult.aiGenerated(),
                aiResult.aiSource(), result.diffSummary(), result.logicAnalysis(),
                result.score(), result.verdict(), result.suggestion());

        return jdbc.queryForObject("SELECT currval('ai_code_review_id_seq')", Long.class);
    }

    private void persistFinding(Long reviewId, Finding f) {
        jdbc.update("""
                INSERT INTO review_finding(review_id, severity, category, file_path, line_range,
                    title, description, code_snippet, suggestion, auto_fixable)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """, reviewId, f.severity(), f.category(), f.filePath(), f.lineRange(),
                f.title(), f.description(), f.codeSnippet(), f.suggestion(), f.autoFixable());
    }

    /**
     * Aggregate AI commit statistics for the day: commit count, total lines,
     * review pass rate and average score (running weighted averages).
     */
    private void updateStats(Long projectId, AiDetectionResult aiResult,
                             int totalLines, int score, String verdict) {
        if (!aiResult.aiGenerated()) return;
        try {
            String source = aiResult.aiSource() != null ? aiResult.aiSource() : "unknown";
            int passRate = "PASS".equals(verdict) ? 100 : 0;
            jdbc.update("""
                    INSERT INTO ai_commit_stats(project_id, stat_date, ai_source, commit_count,
                        total_lines, review_pass_rate, avg_score)
                    VALUES (?, CURRENT_DATE, ?, 1, ?, ?, ?)
                    ON CONFLICT (project_id, stat_date, ai_source)
                    DO UPDATE SET
                        commit_count = ai_commit_stats.commit_count + 1,
                        total_lines = ai_commit_stats.total_lines + EXCLUDED.total_lines,
                        review_pass_rate = (ai_commit_stats.review_pass_rate * ai_commit_stats.commit_count
                            + EXCLUDED.review_pass_rate) / (ai_commit_stats.commit_count + 1),
                        avg_score = (ai_commit_stats.avg_score * ai_commit_stats.commit_count
                            + EXCLUDED.avg_score) / (ai_commit_stats.commit_count + 1)
                    """, projectId, source, totalLines, passRate, (double) score);
        } catch (Exception e) {
            log.warn("failed to update ai stats", e);
        }
    }

    private String detectSource(String message) {
        String lower = message.toLowerCase();
        if (lower.contains("claude")) return "claude";
        if (lower.contains("copilot")) return "copilot";
        if (lower.contains("cursor")) return "cursor";
        if (lower.contains("codebuddy")) return "codebuddy";
        if (lower.contains("chatgpt") || lower.contains("gpt")) return "chatgpt";
        if (lower.contains("gemini")) return "gemini";
        return "ai-unknown";
    }

    // ==================== Records ====================

    public record AiDetectionResult(boolean aiGenerated, String aiSource) {}

    public record CodeReviewResult(int score, String verdict, String diffSummary,
                                     String logicAnalysis, String suggestion,
                                     List<Finding> findings) {}

    public record Finding(String severity, String category, String filePath, String lineRange,
                          String title, String description, String codeSnippet,
                          String suggestion, boolean autoFixable) {}
}
