{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "evotrace.fullname" . }}-secret-reader
  labels:
    {{- include "evotrace.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
    {{- with .Values.rbac.secretNames }}
    resourceNames:
      {{- toYaml . | nindent 6 }}
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "evotrace.fullname" . }}-secret-reader
  labels:
    {{- include "evotrace.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "evotrace.fullname" . }}-secret-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "evotrace.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}